---
- name: Include update verifications
  ansible.builtin.include_tasks: update.yml

- name: Include locales verifications
  ansible.builtin.include_tasks: locales.yml

- name: Include motd verifications
  ansible.builtin.include_tasks: motd.yml

- name: Include scripts verifications
  ansible.builtin.include_tasks: scripts.yml
