---
- name: Verify thermal script attributes
  block:
    - name: Stat thermal script
      ansible.builtin.stat:
        path: /usr/local/bin/thermal
      register: system_thermal_script_stat

    - name: Assert thermal script exists
      ansible.builtin.assert:
        that: system_thermal_script_stat.stat.exists
        fail_msg: "Thermal script does not exist"
        success_msg: "Thermal script exists"

    - name: Assert thermal script is a regular file
      ansible.builtin.assert:
        that: system_thermal_script_stat.stat.isreg
        fail_msg: "Thermal script is not a regular file"
        success_msg: "Thermal script is a regular file"

    - name: Assert thermal script mode
      ansible.builtin.assert:
        that: system_thermal_script_stat.stat.mode == '0755'
        fail_msg: "Thermal script has incorrect mode: {{ system_thermal_script_stat.stat.mode }}"
        success_msg: "Thermal script has correct mode"

    - name: Assert thermal script ownership
      ansible.builtin.assert:
        that:
          - system_thermal_script_stat.stat.pw_name == 'root'
          - system_thermal_script_stat.stat.gr_name == 'root'
        fail_msg: "Thermal script has incorrect ownership: {{ system_thermal_script_stat.stat.pw_name }}:{{ system_thermal_script_stat.stat.gr_name }}"
        success_msg: "Thermal script has correct ownership"

- name: Verify thermal script content
  block:
    - name: Slurp thermal script content
      ansible.builtin.slurp:
        src: /usr/local/bin/thermal
      register: system_thermal_script_content

    - name: Assert thermal script has Unix line endings
      ansible.builtin.assert:
        that: "'\\r\\n' not in (system_thermal_script_content.content | b64decode)"
        fail_msg: "Thermal script has Windows line endings (CRLF)"
        success_msg: "Thermal script has Unix line endings (LF)"
