---
- name: Verify package manager functionality
  block:
    - name: Assert package manager is available
      ansible.builtin.command: "{{ ansible_pkg_mgr }} --version"
      register: system_package_manager_version
      changed_when: false
      failed_when: system_package_manager_version.rc != 0

- name: Include distribution-specific verification tasks
  ansible.builtin.include_tasks: "{{ system_os_family }}/update.yml"
