namespace: scalified
name: setup
version: 2.0.0
readme: README.md
authors:
  - Vladyslav Baidak <vld.x@hotmail.com>

description: Ansible collection for server setup with system configuration and essential tools

license_file: LICENSE

tags:
  - infrastructure
  - linux
  - security
  - storage
  - tools
  - system
  - packages
  - firewall
  - filesystem
  - mail
  - baseline
  - ssl

repository: https://github.com/scalified/ansible-setup-collection
documentation: https://github.com/scalified/ansible-setup-collection
homepage: https://github.com/scalified/ansible-setup-collection
issues: https://github.com/scalified/ansible-setup-collection/issues

build_ignore:
  - "*.gz"
  - .gitignore
  - .github
  - .ansible-lint.yml
  - .ansible
  - molecule
  - tests

dependencies:
  community.crypto: "*"
