namespace: scalified
name: setup
version: 2.7.4
readme: README.md
authors:
  - Vladyslav Baidak <vld.x@hotmail.com>

description: Ansible collection for server setup with system configuration and essential tools

license_file: LICENSE

tags:
  - infrastructure
  - linux
  - security
  - storage
  - tools
  - system
  - packages
  - firewall
  - filesystem
  - mail
  - ssl
  - nut
  - samba
  - baseline

repository: https://github.com/scalified/ansible-setup-collection
documentation: https://github.com/scalified/ansible-setup-collection
homepage: https://github.com/scalified/ansible-setup-collection
issues: https://github.com/scalified/ansible-setup-collection/issues

build_ignore:
  - "*.gz"
  - .claude
  - .gitignore
  - .github
  - .ansible-lint.yml
  - .ansible
  - CLAUDE.md
  - molecule
  - tests

dependencies:
  ansible.posix: "*"
  community.general: "*"
  community.crypto: "*"
  community.docker: "*"
