---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.crypto
  - name: community.docker
    version: "4.8.2" # https://github.com/ansible-community/molecule-plugins/issues/346
