---
- name: Install bash packages
  ansible.builtin.package:
    name:
      - bash-completion
    state: present
  retries: 3
  delay: 10
  become: true

- name: Create bash autocompletion directory
  ansible.builtin.file:
    dest: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Ensure bashrc file exists
  block:
    - name: Stat if .bashrc file
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.bashrc"
      register: packages_bashrc_stat

    - name: Copy .bashrc from skeleton when missing
      ansible.builtin.copy:
        src: /etc/skel/.bashrc
        dest: "{{ ansible_env.HOME }}/.bashrc"
        mode: '0644'
        remote_src: true
      when: not packages_bashrc_stat.stat.exists

- name: Configure bash aliases
  ansible.builtin.template:
    src: .bash_aliases
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    mode: "0644"

- name: Add Bash aliases sourcing
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    append_newline: true
    prepend_newline: true
    marker: "# BASH ALIASES {mark}"
    block: |
      if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
      fi
