---
- name: Packages Role - Packages installation and configuration
  ansible.builtin.debug:
    msg:
      - "============================================"
      - "  Packages: Installation and Configuration"
      - "============================================"

- name: Include packages tasks
  ansible.builtin.include_tasks: packages.yml

- name: Include VIM tasks
  ansible.builtin.include_tasks: vim.yml

- name: Include AGE tasks
  ansible.builtin.include_tasks: age.yml
  when: packages_age_private_key_file is defined
