- name: Install VIM package
  ansible.builtin.package:
    name: vim
    state: present
  retries: 3
  delay: 10
  become: true

- name: Deploy VIM configuration
  ansible.builtin.copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0644'
