# System
system_os_family: "{{ ansible_os_family | lower }}"

system_motd_contacts:
  - name: "John Doe"
    position: "System Administrator"
    email: "john.doe@example.com"
    mobile: "+1-555-123-4567"
  - name: "Jane Smith"
    position: "Security Officer"
    email: "jane.smith@example.com"
    mobile: "+1-555-999-0000"

# Packages
packages_list:
  - net-tools
packages_bash_aliases:
  - alias: "testls"
    command: "ls -la"
    comment: "Test alias for detailed listing"
  - alias: "testgrep"
    command: "grep -n"
    comment: "Test alias for grep with line numbers"
  - alias: "testalias"
    command: "echo 'Hello from test alias'"

# Firewall
firewall_ufw_profiles:
  - dhcp
  - docker
  - http
  - l2tp
  - mongodb
  - mysql
  - nginx
  - ntp
  - openvpn
  - postgresql
  - pptp
  - redis
  - samba
  - sip
  - snmp
  - syslog
  - whois

# FS
fs_files:
  - path: "/home/test"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  - path: "/home/test/file.txt"
    state: "touch"
    owner: "root"
    group: "root"
    mode: "0644"
    modification_time: preserve
    access_time: preserve
fs_mount_auto_remount_scripts_dir: /usr/local/lib/auto-remount

# Mail
mail_smtp_server: "smtp.example.com"
mail_smtp_port: 587
mail_smtp_username: "testuser"
mail_smtp_password: "testpassword"
mail_hostname: "mail.example2.com"
mail_recipient: "test@example.com"

# SSL
ssl_domain: "test.example.com"
ssl_keys_ca_name: "ca.key"
ssl_keys_server_name: "server.key"
ssl_certs_server_generate: true
ssl_certs_ca_name: "ca.crt"
ssl_certs_server_name: "server.crt"
ssl_bundle_generate: true
ssl_bundle_name: "bundle.crt"

# Docker
docker_user: "{{ ansible_user_id }}"
docker_system_prune_cron: ""

# Samba
samba_interfaces:
  - "lo"
  - "eth0"
samba_server_string: "Samba TEST Server"
samba_workgroup: "TESTWORKGROUP"
samba_netbios_name: "TESTNAME"
samba_password: "testpassword"
samba_shares:
  - name: documents
    path: /srv/samba/documents
    comment: "Shared documents"
    owner: root
    group: root
  - name: media
    path: /srv/samba/media
    comment: "Shared media files"
    writeable: "no"
    owner: root
    group: root

# NUT
nut_mode: standalone
nut_ups_name: "testups"
nut_ups_config:
  driver: usbhid-ups
  port: auto
  vendor: EATON
  vendorid: "1234"
  product: Ellipse PRO
  productid: "AAAA"
  serial: "ABC12345678"
  bus: "001"
nut_ups_config_extra:
  extra: extratest
nut_users_admin_name: testadmin
nut_users_admin_password: testadminpass
nut_users_monitor_name: testupsmon
nut_users_monitor_password: testupsmonpass
nut_users_upsmon_runas_name: testnutmon
nut_upsmon_server: localhost
nut_upsmon_port: 3493
nut_upsmon_priority: secondary
