system_os_family: "{{ ansible_os_family | lower }}"

system_motd_contacts:
  - name: "John Doe"
    position: "System Administrator"
    email: "john.doe@example.com"
    mobile: "+1-555-123-4567"
  - name: "Jane Smith"
    position: "Security Officer"
    email: "jane.smith@example.com"
    mobile: "+1-555-999-0000"

system_bash_aliases:
  - alias: "testls"
    command: "ls -la"
    comment: "Test alias for detailed listing"
  - alias: "testgrep"
    command: "grep -n"
    comment: "Test alias for grep with line numbers"
  - alias: "testalias"
    command: "echo 'Hello from test alias'"

packages_list:
  - net-tools

fs_files:
  - path: "/home/test"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  - path: "/home/test/file.txt"
    state: "touch"
    owner: "root"
    group: "root"
    mode: "0644"
    modification_time: preserve
    access_time: preserve
fs_mount_auto_remount_scripts_dir: /usr/local/lib/auto-remount
