---
- name: Gather service facts
  ansible.builtin.service_facts:
  become: true

- name: Disable Apache HTTPD service
  ansible.builtin.service:
    name: httpd
    state: stopped
    enabled: false
  become: true
  when:
    - system_systemd_managed
    - services.httpd is defined
