---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Files and directories management
  company: Scalified
  license: MIT
  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - filesystem
    - files
    - directories
    - storage
    - mount
    - cifs

dependencies:
  - role: scalified.setup.system
