---
- name: Deploy scripts
  ansible.builtin.copy:
    src: "{{ script }}"
    dest: "/usr/local/bin/{{ script }}"
    owner: root
    group: root
    mode: '0755'
  become: true
  loop:
    - thermal
  loop_control:
    loop_var: script
