---
- name: Install timesyncd package
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present
  retries: 3
  delay: 10
  become: true

- name: "Set timezone to {{ system_timezone }}"
  community.general.timezone:
    name: "{{ system_timezone }}"
  become: true

- name: Enable and start timesyncd service
  ansible.builtin.systemd_service:
    name: systemd-timesyncd
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Wait for time synchronization
  ansible.builtin.command: timedatectl show --property=NTP --value
  register: system_time_ntp_sync_status
  until: system_time_ntp_sync_status.stdout | lower in ['yes', 'true']
  retries: 5
  delay: 10
  changed_when: false

- name: Display time synchronization status
  ansible.builtin.debug:
    msg: |-
      Time synchronization status: {{ system_time_ntp_sync_status.stdout | default('unknown') }}
      {%- if system_time_ntp_sync_status.stdout | lower not in ['yes', 'true'] %}
      Warning: NTP synchronization may still be in progress{% endif %}
