---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Manages SSL certificates and keys
  company: Scalified
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - ssl
    - certificates

dependencies:
  - role: scalified.setup.system
