---
- name: Verify Docker system prune script and configuration
  block:
    - name: Verify Docker system prune script exists
      ansible.builtin.stat:
        path: /usr/local/bin/docker-system-prune
      register: prune_script

    - name: Assert Docker system prune script exists and is executable
      ansible.builtin.assert:
        that:
          - prune_script.stat.exists
          - prune_script.stat.isreg
          - prune_script.stat.mode == '0755'
        fail_msg: "Docker system prune script does not exist or is not executable"
        success_msg: "Docker system prune script exists and is executable"

    - name: Read prune script content
      ansible.builtin.slurp:
        src: /usr/local/bin/docker-system-prune
      register: script_content_slurp

    - name: Assert prune script contains expected commands
      ansible.builtin.assert:
        that:
          - "'docker system prune --all --volumes --force' in (script_content_slurp.content | b64decode)"
        fail_msg: "Prune script content does not match expected configuration"
        success_msg: "Prune script content matches expected configuration"
