---
- name: Include distribution-specific verification tasks
  ansible.builtin.include_tasks: "{{ system_os_family }}/setup.yml"

- name: Verify Docker packages installed
  block:
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: "Assert Docker package installed"
      ansible.builtin.assert:
        that: "'{{ package }}' in ansible_facts.packages"
        fail_msg: "{{ package }} package is not installed"
        success_msg: "{{ package }} package is installed"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      loop_control:
        loop_var: package

- name: Verify docker user in docker group
  block:
    - name: Get user groups
      ansible.builtin.command: "id -Gn {{ docker_user }}"
      register: docker_user_groups
      changed_when: false

    - name: Assert docker user is in the docker group
      ansible.builtin.assert:
        that: docker_user in upsmon_runas_groups.stdout.split()
        fail_msg: "{{ docker_user }} user is not in the docker group"
        success_msg: "{{ docker_user }} user is in the docker group"
