---
- name: Update package cache
  ansible.builtin.dnf:
    update_cache: true
  retries: 3
  delay: 10
  become: true

- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest # noqa package-latest
  retries: 3
  delay: 30
  become: true
  changed_when: false

- name: Remove unnecessary packages
  ansible.builtin.dnf:
    autoremove: true
  become: true
  when: system_update_autoremove

- name: Request reboot after updates
  ansible.builtin.debug:
    msg: "Updates completed, checking if reboot is needed"
  notify: "system : request reboot"
