---
- name: Firewall Role - setup and configuration
  ansible.builtin.debug:
    msg:
      - "======================================"
      - "  Firewall: setup and configuration"
      - "======================================"

- name: Include distribution-specific tasks
  ansible.builtin.include_tasks: "{{ system_os_family }}/main.yml"
