---
- name: Setup Test
  hosts: all
  gather_facts: true
  roles:
    - scalified.setup.system
    - scalified.setup.packages
    - scalified.setup.firewall
    - scalified.setup.fs
    - scalified.setup.mail
