---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Molecule Tests Information
      ansible.builtin.debug:
        msg: "Running verification tests on {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: "Run verification tests for {{ role }}"
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - system
        - packages
      loop_control:
        loop_var: role

    - name: Molecule Tests Summary
      ansible.builtin.debug:
        msg:
          - "========================"
          - "  VERIFICATION RESULTS  "
          - "========================"
          - "  ✓ System:    PASSED   "
          - "  ✓ Packages:  PASSED   "
          - "========================"
