---
- name: Include distribution-specific tasks
  ansible.builtin.include_tasks: "{{ system_os_family }}/cgi.yml"

- name: Install NUT CGI package
  ansible.builtin.package:
    name:
      - nut-cgi
    state: present
  retries: 3
  delay: 10
  become: true

- name: Deploy NUT CGI configurations
  ansible.builtin.template:
    src: "{{ file }}"
    dest: "{{ nut_dir }}/{{ file }}"
    owner: root
    group: nut
    mode: "640"
  loop:
    - hosts.conf
    - upsset.conf
  loop_control:
    loop_var: file
  become: true
