---
- name: Add UPSMON process user
  ansible.builtin.user:
    name: "{{ nut_users_upsmon_runas_name }}"
    create_home: false
    group: nut
  become: true

- name: Deploy NUT UPSMON configuration
  ansible.builtin.template:
    src: upsmon.conf
    dest: "{{ nut_dir }}/upsmon.conf"
    owner: root
    group: nut
    mode: "0640"
  become: true

- name: Enable NUT UPSMON service
  ansible.builtin.systemd_service:
    name: nut-monitor
    enabled: true
    daemon-reload: true
    state: started
  become: true
  when: system_systemd_managed
