---
- name: Include SSL setup verifications
  ansible.builtin.include_tasks: setup.yml

- name: Include SSL CA verifications
  ansible.builtin.include_tasks: ca.yml

- name: Include SSL server verifications
  ansible.builtin.include_tasks: server.yml

- name: Include SSL bundle verifications
  ansible.builtin.include_tasks: bundle.yml

- name: Include SSL clients verifications
  ansible.builtin.include_tasks: client.yml
  loop: "{{ ssl_clients }}"
  loop_control:
    loop_var: client
