---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Firewall setup and configuration
  company: Scalified
  license: MIT
  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - firewall
    - security
    - networking
    - ufw
    - firewalld
    - ports
    - rules

dependencies:
  - role: scalified.setup.system
