---
- name: Verify auto-remount script attributes
  block:
    - name: Stat auto-remount script
      ansible.builtin.stat:
        path: /usr/local/bin/auto-remount
      register: fs_auto_remount_script

    - name: Verify auto-remount script exists
      ansible.builtin.assert:
        that: fs_auto_remount_script.stat.exists
        fail_msg: "Auto remount script does not exist"
        success_msg: "Auto remount script exists"

    - name: Verify auto-remount script is a regular file
      ansible.builtin.assert:
        that: fs_auto_remount_script.stat.isreg
        fail_msg: "Auto remount script is not a regular file"
        success_msg: "Auto remount script is a regular file"

    - name: Verify auto-remount script mode
      ansible.builtin.assert:
        that: fs_auto_remount_script.stat.mode == '0755'
        fail_msg: "Auto remount script mode is incorrect: {{ fs_auto_remount_script.stat.mode }}"
        success_msg: "Auto remount script mode is correct"

    - name: Verify auto-remount script ownership
      ansible.builtin.assert:
        that:
          - fs_auto_remount_script.stat.pw_name == 'root'
          - fs_auto_remount_script.stat.gr_name == 'root'
        fail_msg: "Auto remount script ownership is incorrect: {{ fs_auto_remount_script.stat.pw_name }}:{{ fs_auto_remount_script.stat.gr_name }}"
        success_msg: "Auto remount script ownership is correct"

- name: Verify auto-remount script content
  block:
    - name: Slurp auto-remount script content
      ansible.builtin.slurp:
        src: /usr/local/bin/auto-remount
      register: fs_auto_remount_script_content

    - name: Assert auto-remount script has Unix line endings
      ansible.builtin.assert:
        that: "'\\r\\n' not in (fs_auto_remount_script_content.content | b64decode)"
        fail_msg: "Auto remount script contains Windows line endings (CRLF)"
        success_msg: "Auto remount script has Unix line endings (LF)"

- name: Verify remount scripts directory attributes
  block:
    - name: Stat remount scripts directory
      ansible.builtin.stat:
        path: "{{ fs_mount_auto_remount_scripts_dir }}"
      register: fs_auto_remount_dir

    - name: Verify remount scripts directory exists
      ansible.builtin.assert:
        that: fs_auto_remount_dir.stat.exists
        fail_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} does not exist"
        success_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} exists"
    
    - name: Verify remount scripts directory is a directory
      ansible.builtin.assert:
        that: fs_auto_remount_dir.stat.isdir
        fail_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} is not a directory"
        success_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} is a directory"
    
    - name: Verify remount scripts directory mode
      ansible.builtin.assert:
        that: fs_auto_remount_dir.stat.mode | string == '0755'
        fail_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} mode is incorrect: {{ fs_auto_remount_dir.stat.mode }}"
        success_msg: "Remount scripts directory {{ fs_mount_auto_remount_scripts_dir }} mode is correct"

    - name: Verify remount scripts directory ownership
      ansible.builtin.assert:
        that:
          - fs_auto_remount_dir.stat.pw_name == 'root'
          - fs_auto_remount_dir.stat.gr_name == 'root'
        fail_msg: "Remount scripts directory ownership is incorrect: {{ fs_auto_remount_dir.stat.pw_name }}:{{ fs_auto_remount_dir.stat.gr_name }}"
        success_msg: "Remount scripts directory ownership is correct"
