---
- name: Install mail packages
  ansible.builtin.package:
    name:
      - exim4
      - mailutils
    state: present
  retries: 3
  delay: 10
  become: true

- name: Configure exim4 authentication
  ansible.builtin.template:
    src: "{{ system_os_family }}/passwd.client"
    dest: /etc/exim4/passwd.client
    mode: "0640"
  become: true

- name: Configure exim4 rewrite rules
  ansible.builtin.template:
    src: "{{ system_os_family }}/99_exim4-config_rewrite_rules"
    dest: /etc/exim4/conf.d/rewrite/99_exim4-config_rewrite_rules
    mode: "0644"
  become: true

- name: Add exim4 configuration
  ansible.builtin.template:
    src: "{{ system_os_family }}/update-exim4.conf.conf"
    dest: /etc/exim4/update-exim4.conf.conf
    mode: "0644"
  become: true
  notify: update exim4 configuration
