- name: Generate SSL server private key
  community.crypto.openssl_privatekey:
    path: "{{ ssl_keys_server_path }}"
    owner: "{{ ssl_keys_server_owner }}"
    group: "{{ ssl_keys_server_group }}"
    mode: "{{ ssl_keys_server_mode }}"
  become: true
  no_log: true
  register: ssl_keys_server

- name: Configure SSL server CSR
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ ssl_keys_server_path }}"
    common_name: "{{ ssl_csr_server_common_name }}"
    country_name: "{{ ssl_csr_server_country_name }}"
    state_or_province_name: "{{ ssl_csr_server_state_or_province_name }}"
    locality_name: "{{ ssl_csr_server_locality_name }}"
    organization_name: "{{ ssl_csr_server_organization_name }}"
    organizational_unit_name: "{{ ssl_csr_server_organizational_unit_name }}"
    email_address: "{{ ssl_csr_server_email_address }}"
    basic_constraints:
      - CA:FALSE
    subject_alt_name: "{{ ssl_csr_server_subject_alt_name }}"
    use_common_name_for_san: false
    extended_key_usage: TLS Web Server Authentication
    create_subject_key_identifier: true
  become: true
  changed_when: ssl_keys_server.changed
  no_log: true
  register: ssl_server_csr

- name: Generate SSL server certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_certs_server_path }}"
    privatekey_path: "{{ ssl_keys_server_path }}"
    csr_content: "{{ ssl_server_csr.csr }}"
    provider: ownca
    ownca_path: "{{ ssl_certs_ca_path }}"
    ownca_privatekey_path: "{{ ssl_keys_ca_path }}"
    ownca_not_after: "{{ ssl_certs_not_after }}"
    owner: "{{ ssl_certs_server_owner }}"
    group: "{{ ssl_certs_server_group }}"
    mode: "{{ ssl_certs_server_mode }}"
  become: true
  no_log: true
