---
- name: Install SSL packages
  ansible.builtin.package:
    name:
      - ca-certificates
      - python3-cryptography
    state: present
  retries: 3
  delay: 10
  become: true

- name: Create SSL cert group
  ansible.builtin.group:
    name: ssl-cert
    state: present
  become: true

- name: Create SSL keys directories
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: root
    group: ssl-cert
    mode: "0710"
  loop:
    - "{{ ssl_keys_ca_dir }}"
    - "{{ ssl_keys_server_dir }}"
  become: true
  loop_control:
    loop_var: dir

- name: Create SSL certificates directories
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ ssl_certs_ca_dir }}"
    - "{{ ssl_certs_server_dir }}"
  become: true
  loop_control:
    loop_var: dir

- name: Create SSL client keys directory
  ansible.builtin.file:
    path: "{{ ssl_keys_clients_dir }}"
    state: directory
    owner: root
    group: ssl-cert
    mode: "0710"
  become: true
  when: ssl_clients | length > 0

- name: Create SSL client certificates directory
  ansible.builtin.file:
    path: "{{ ssl_certs_clients_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  when: ssl_clients | length > 0
