---
- name: Inspect Docker Buildx platforms
  ansible.builtin.command: docker buildx inspect --bootstrap
  register: docker_qemu_buildx_inspect
  changed_when: false
  become: true

- name: Configure QEMU emulation
  community.docker.docker_container:
    name: docker-qemu
    image: tonistiigi/binfmt
    command: --install all
    privileged: true
    detach: false
    cleanup: true
    pull: missing
  become: true
  when: >-
    ['linux/amd64', 'linux/arm64'] | reject('in', docker_qemu_buildx_inspect.stdout) | list | length > 0
