---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ system_update_cache_valid_time }}"
  retries: 3
  delay: 10
  become: true

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: "{{ system_update_type }}"
    autoremove: "{{ system_update_autoremove }}"
    autoclean: "{{ system_update_autoclean }}"
  retries: 2
  delay: 30
  become: true
  notify: "system : request reboot"
