---
galaxy_info:
  author: Vladyslav Baidak <vld.x@hotmail.com>
  description: Baseline role that coordinates the execution of multiple essential roles for system setup and configuration
  company: Scalified
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - baseline

dependencies:
  - role: scalified.setup.system
  - role: scalified.setup.packages
  - role: scalified.setup.firewall
    when: baseline_firewall_enabled
  - role: scalified.setup.fs
  - role: scalified.setup.mail
    when: baseline_mail_enabled
