---
- name: Verify HTTPD service is stopped
  block:
    - name: Gather service facts
      ansible.builtin.service_facts:
      become: true

    - name: Assert HTTPD service is stopped
      ansible.builtin.assert:
        that: services.httpd.state is not defined or services.httpd.state == 'stopped'
        fail_msg: "HTTPD service is not stopped"
        success_msg: "HTTPD service is stopped or not defined"
