---
- name: Include packages verifications
  ansible.builtin.include_tasks: packages.yml

- name: Include vim verifications
  ansible.builtin.include_tasks: vim.yml

- name: Include age verifications
  ansible.builtin.include_tasks: age.yml
  when: packages_age_private_key_file is defined
